### ISSUE TITLE
Wrong data in the dashboard

### ISSUE THREAD

**Issue by akiva-skolnik** [aws-deepracer-community/deepracer-for-cloud#186] opened 2024-07-15 20:34 UTC
It also happened with several other completed episodes.
![image](https://github.com/user-attachments/assets/cfbe473b-fa45-4a96-8538-913bd22a54ba)

**Comment by larsll** [comment] 2024-07-17 05:50
Closing as duplicate of #185

**Closed by larsll** 2024-07-17 05:50 UTC
