### ISSUE TITLE
Simulation taking too large of a timestep? 

### ISSUE THREAD

**Issue by aiaarif** [aws-deepracer-community/deepracer-for-cloud#131] opened 2023-04-08 13:46 UTC
I am training a model in continuous action space with speed setting (min 0.5, max 1.0). Based on all the discussions in the community, a single step should be 1/15 seconds. Even at max speed, the distance between consecutive points should be at most (1 m/s)*(1 s/15 step) = 0.06 m/step. But I see the distance between the consecutive points is too high in local training. Attached is two graph showing car positions and distance between points in each step in one episode of training.

I am using 5.1.0-cpu for sagemaker, 5.1.0-cpu-avx2 for robomaker

![image](https://user-images.githubusercontent.com/5774830/230724174-6fb367b2-da7d-46f7-947b-37ef9f1f8915.png)
![image](https://user-images.githubusercontent.com/5774830/230724202-3902c458-323f-4555-b5fc-d27cd6c43adc.png)

**Comment by aiaarif** [comment] 2023-04-12 14:26
update: This issue might be related to swarm mode. In swarm mode, I was able to access all the camera feeds without starting the viewer. I had these embedded on a web page to check on the progress.
Today I am trying the compose mode with the -v option since I can't access the viewer otherwise. With this change, this issue seems to be resolved and I am getting average approximate 15 steps a second instead of 6 that I was getting previously.

**Comment by larsll** [comment] 2023-05-20 10:37
This is likely more down to performance of computer; it is known that if the CPU is overloaded the steps will be unevenly spread out, and you will get these kind of pictures. Closing as definitively not a bug in this repository. (If a true bug this would be part of the deepracer-simapp repository.)

**Closed by larsll** 2023-05-20 10:37 UTC
